### ISSUE TITLE
extra-cmake-modules 1.6.0 fail 

### ISSUE THREAD

**Issue by demmm** [KaOSx/calamares#63]
With e-c-m from frameworks 5.6.0 the install paths are not honored correctly.  Even-though project is set to install in /usr, with the libdir set to /usr/lib, part of the modules are installed in /usr/lib64, other parts in /usr/lib.
Downgrading to e-c-m 1.5.0, all installs correctly.

**Comment by kkofler** [comment]
This is an ECM regression. This patch:
http://pkgs.fedoraproject.org/cgit/extra-cmake-modules.git/plain/extra-cmake-modules-1.6.0-KDEInstallDirs-no-unset.patch
fixes a similar problem (probably different symptoms of the same issue) for us in Fedora.

**Comment by kkofler** [comment]
https://bugs.kde.org/show_bug.cgi?id=342717

**Comment by demmm** [comment]
Fixed with upstream ECM 1.6.1 release
