### ISSUE TITLE
When installing from a live usb to another usb as destination AND NO boot partition is specified grub is not able to install on deive and breaks python script, when it returns 1.

### ISSUE THREAD

**Issue by freemint** [KaOSx/calamares#65]

**Comment by demmm** [comment]
Please create proper reports, a long title with zero info, logs, what ISO used, UEFI or BIOS install is not useful.
This however looks like correct behavior of the installer.  Of course you need to specify a boot partition if installing to such a non-standard option.

**Comment by demmm** [comment]
Closing as not a bug report, no response from submitter about providing any info.
