### ISSUE TITLE
Installation failed !! 

### ISSUE THREAD

**Issue by krishnasut** [KaOSx/calamares#71]
Calamares failed to copy files and the installation process is aborted showing  errors. 
To avoid such unwanted condition  (1), fisrt i erase all partitions on  my Hard Disk , (2) then reboot the system and (3) finally  start fresh install. 
Is there any fix ? 

md5sum of my ISO is - 47c3e2f05dd02a4545b7d5e97d879f53

blkid -- 
/dev/sda1: UUID="12E3-F868" TYPE="vfat" PARTUUID="2d189d62-ac5f-4748-8ae7-e8cfb27572d3"
/dev/sda2: UUID="cf29b84f-c07c-4515-92f6-7e5b44475b31" TYPE="ext4" PARTUUID="ed7bcd19-71f0-4981-874c-24831bc48c2d"
/dev/sda3: UUID="56f010de-d79c-4602-a2de-79b52cb66cfe" TYPE="swap" PARTUUID="02e97669-5573-41db-8353-090b0b7b344d"
/dev/sdb1: LABEL="storage" UUID="9356b303-9538-4f78-a179-4c0dcc6048d9" TYPE="ext4" PARTUUID="3eefe9b0-3a86-4005-98f7-c9bdbccf2ac1"
/dev/sdc1: UUID="2016-06-22-20-27-56-00" LABEL="KAOS_20160622" TYPE="iso9660" PTUUID="3d6a0a9c" PTTYPE="dos" PARTUUID="3d6a0a9c-01"
/dev/sdc2: SEC_TYPE="msdos" LABEL="KAOS_EFI" UUID="AF6A-4229" TYPE="vfat" PARTUUID="3d6a0a9c-02"
/dev/loop0: TYPE="squashfs"
/dev/loop1: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"

**Comment by demmm** [comment]
See https://kaosx.us/docs/ to create a full report needed for installations issues.
installation.log will be needed. How the Live media was created.

**Comment by demmm** [comment]
Since no response to requests for needed info and the described fail is very well known when Live media is created with non-supported software (rufus mainly), closing as invalid.
