### ISSUE TITLE
Python module error 'Nonetype' has no attribute 'Group' while installation 

### ISSUE THREAD

**Issue by Karan1458** [KaOSx/calamares#72]
First run to KaOS installation. 

PC configs
$lspci 
00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation C220 Series Chipset Family H81 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 11)

Chosen options :

- Installing via select a partition

- Manual Partitioning with ext4 type

 

Installer failed with the following screen. 
![screenshot_20160904_065338](https://cloud.githubusercontent.com/assets/7886431/18229554/166d339a-726d-11e6-9e48-7952928eabbf.png)

**Comment by Karan1458** [comment]
More info on disks layout 
$blkid  - [https://goo.gl/BEMcn8](https://goo.gl/BEMcn8)
$fdisk -l - [https://goo.gl/eUmBVG](https://goo.gl/eUmBVG)

**Comment by Karan1458** [comment]
Couldn't wait so long for the response. 

Update the victim file 
![screenshot_20160904_080642](https://cloud.githubusercontent.com/assets/7886431/18229836/903b8bd2-7276-11e6-94d6-6e5f87006b6d.png)

Official website is providing rolling releases to end user. Release version was missing while installation.

**Comment by demmm** [comment]
How was the Live media created?  Release version is read during the instal as a var, no need to hardcode.

**Comment by Karan1458** [comment]
Live Media was created with Rufus. I have downloaded it from official site. 
$lsb_release says it's rolling edition. I guessed it's not getting any string, So i provided him in hardcode. Minor issue but stopped the complete installation.

**Comment by demmm** [comment]
Rufus, as expected....
It is not a supported way of creating live media and known to fail.  This time your media was corrupted for this, next live media you create with rufus will fail somewhere else.
This is why it is listed as not supported.
To create reliable media, follow the links as posted with every Release Notes, News article for a new ISO or the Download page.
