### ISSUE TITLE
Put wifi driver for mac air (and mac air like) in default package ISO.

### ISSUE THREAD

**Issue by Burais** [KaOSx/calamares#75]
#### Submission type

  - [ ] Feature Request
=> Put in the default package the wifi driver for broadcom wifi card in order to have internet at the installation for macbook air. Their is no RJ12 port on this type of thin PC.

#### KaOS ISO date you are having issues with or have a request for

> december 2016 (just before the KaOS 2017.01 ISO)

#### How did you create the Live Media?
> on a usbkey

#### Did you check the md5sum of the downloaded ISO?
>no problem with the iso

#### Describe the issue you encountered

> installation on my mac air that haven't any RJ12 cable port.
I need to by a usb adaptator to plug RJ 12 cable to have internet in order to install.... the wifi driver for the broadcom wifi

#### Steps to reproduce the problem

>not a bug but a request.

#### Include the installation.log:
 * Live mode: `~/installation.log`
 * Installed System: `/var/log/installation.log`

> …

**Comment by demmm** [comment]
First of, this is not an installer request but [Live ISO](https://github.com/KaOSx/live-uefi/issues)

Won't be implemented though, non-free, license encumbered driver will not be forced upon all users while the free, in-kernel option works as good or better for most.

**Comment by Burais** [comment]
sorry to not understand but : 
-> no it is a "installer request" my computer has kaos on hard drive (I'm gona regret in few time)
-> I have installed it from a USBKey, so yes I had to launch a live distro from a usb key and install it with the help of.. how do you call it ? an installer.
-> I don't want to force any one, It should be an option proposed to user, without any network it is a pain, a package we can install or not. But you forced me to bye a adaptater because you don't want to put a package "in the case of". Ok I see.
The free one does not work for the wifi card in apple, I'm not the only one see google.

Well sorry for my stupid request do what you want.
