### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Amethi** [KaOSx/calamares#76]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### KaOS ISO date you are having issues with or have a request for

> KaOS 2017.01 ISO

#### How did you create the Live Media?

> Using rufus-2.11.exe on Windows 10

#### Did you check the md5sum of the downloaded ISO?

> No

#### Describe the issue you encountered

> Installation gets to the end and a error dialog pops up. Behind it text says the installation was successful and to reboot. Click Close on the dialog, reboot the system and it just sits at a black screen with flashing prompt.

Photos:
[http://imgur.com/xvBEXoB](url)

[http://imgur.com/WuUVjeG](url)

Machine is an Intel 3rd gen i5, z77 chipset based pc with 8gb ram and an OCZ TRION 100 SSD.

#### Steps to reproduce the problem

> I've tried re-installing and get the same experience.

#### Include the installation.log:
 * Live mode: `~/installation.log`
 * Installed System: `/var/log/installation.log`

> No /var/log/installation.log file exists, just four directories: cups, journal, old and samba, and there's no files in those.

**Comment by demmm** [comment]
Read the warnings all over KaOS about Rufus.

**Comment by Amethi** [comment]
Just read that in the forum. Doh. Too eager :)
