### ISSUE TITLE
ERROR: Root device mounted successfully, but /sbin/init does not exist.

### ISSUE THREAD

**Issue by 81909ce2298f99ddafa37936ba43eaac** [KaOSx/calamares#78]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### KaOS ISO date you are having issues with or have a request for

> 20170217

#### How did you create the Live Media?

> GnomeBaker

#### Did you check the md5sum of the downloaded ISO?

>yes

#### Describe the issue you encountered

>After installing KaOS sucessfully with separate partitions for "/", "/usr", "/var" and "/home" the first start from hard disk drive failed with the following error message:

> ERROR: Root device mounted successfully, but /sbin/init does not exist.

"/sbin" in KaOS (and Arch Linux) is a symlink to "/usr/bin" (btw: I hate this change). This means that unless /usr is mounted, /usr/sbin/init will not exist. The installer doesn't take care of this fact when creating the initial ramdisk. 

The problem can be fixed by changing the hooks and modifying "/etc/fstab":

1. In "/etc/fstab" the partion "/usr" has to be mounted with a passno of 0.

For the users, who are not so familiar with linux: The passno (fsck order) is the last column in "/etc/fstab" in each row.  Hence the corresponding line should look like

UUID=a304512f-e1ce-499e-920f-5c18cd53969d /usr                    ext4    defaults,noatime     0 **0**
...

2. In "/etc/mkinitcpio.conf" the HOOKS line has to be extended with "usr" and you have to make sure that "fsck" and "block" are in this list, too.

3. Rebuild the initial ramdisk by executing: mkinitcpio -p linux

#### Steps to reproduce the problem
> Install KaOS with a separate partition for /usr

#### Include the installation.log:
> Sorry, I don't have a log file.

**Comment by demmm** [comment]
You seem to be confused what distrubution you wanted to install.  This is not ArchLinux or any of it's many derivatives. KaOS certainly does not use any symlinks to /usr. If you had planned to install Arch, make sure to select another distribution than KaOS

If you do not have the installation.log then this install has many more issues thne just /usr not mounted, log is always copied to /var/log.
With this install using an unsupported way to create live media and with no logs, this bug report is not usable.

Make sure to read what KaOS is and is not, see the website and check the About, Download and Documentation sections.
https://kaosx.us/

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
I know which distribution I have installed. I only mentioned that the file system layout is almost identical to Arch Linux as far as I know. That's all. 

I didn't use an unsupported way to create the dvd media or you documentation (https://kaosx.us/docs/dvd/) is incomplete. 

To be honest I feel that your don't take me seriously. I think my posting doesn't look like a report written by a novice. 

I know that I didn't submit a log file. The reason is simple. It was just a testing system without internet access and I didn't have an usb media to transfer the log file. 

I would like to ask a question: If the HOOK option in "/etc/mkinitcpio.conf" doesn't contain "usr", which was the case after the installation of KaOS, why should the system mount "/usr" on startup automatically before executing "/sbin/init"?

**Comment by demmm** [comment]
Again, nothing that can be done without logs, and as mentioned in your other reports, start with correctly booting install media.  Don't start with hacks.

**Comment by demmm** [comment]
Your own words to make the broken media boot:
```
I took a look at the file system and there wasn't a directory "/dev/disk/by-label/". I was able to fix the problem by entering the following commands:

mkdir /dev/disk/by-label/

ln -s /dev/sr0 /dev/disk/by-label/KAOS_20170217

exit (Shell)
```
Having to do some hacks to make it boot is clearly broken, what else do you want me to say?  
Unless you can show you use install media that just boots there is no use to keep continuing with this bug report.
Re-open if you have issues and an installation.log of an install that was created with live media that boots without hacks/symlinks.

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
> Having to do some hacks to make it boot is clearly broken, what else do you want me to say?

I want say that there's most probably a bug in the installer. That is the reason why I can "start with correctly booting install media". I can boot from the install media (DVD). Grub starts fine and I assume the initial ram disk is working, too. That's the reason why I got a (root) shell after starting the live system in the boot loader of the dvd media. The hacks mentioned above were made within this shell. 

If you don't want to care about the problem without a log, my only chance is to reinstall the system from dvd. 

I know it sounds a little bit wired but I guess the problem only occurs if there is no hard disk with a least one partition attached to the computer. Hopefully I will find the time for further tests in the next days.
