### ISSUE TITLE
Calamares crash

### ISSUE THREAD

**Issue by realloki** [KaOSx/calamares#79]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### KaOS ISO date you are having issues with or have a request for

> KaOS 2017.04 (both variants, the normal one and the wayland

#### How did you create the Live Media?

> dd under Linux onto an USB stick

#### Did you check the md5sum of the downloaded ISO?

> no.

#### Describe the issue you encountered

> calamares crashed on two machines with two different ISO origins. Started from welcome and standalone. Pre- and post-updates on the live-system.

#### Steps to reproduce the problem

> dd an ISO on an USB-stick, just boot, start install. Crash.

#### Include the installation.log:

See Bug Report 7a95b45f-72dd-c510-4f03806c-57a25a90
there must be an other Bug Report created on the other machine.

 * Live mode: `~/installation.log`

13:33:43 [1]: Calamares version: 3.1.0.20170409-git-master-e44b7e3 
13:33:43 [1]: Default font ===== 
Pixel size:    -1 
Point size:    10 
Point sizeF:   10 
Font family:   "Noto Sans" 
Metric height: 18 
13:33:43 [1]: Font height: 18 
13:33:43 [1]: Available languages: ("ast", "ca", "cs", "de", "en", "es", "es_AR", "fr", "hr", "hu", "id_ID", "it", "nl_NL", "pl", "pt_BR", "pt_PT", "ro_RO", "ru", "sl", "sr_RS", "sv", "tr_TR") 
m_crashReporterWChar: /usr/bin/../libexec/calamares_crash_reporter13:33:43 [1]: CalamaresApplication thread: 0xdebad0 
13:33:43 [1]: Using log file: "/root/.cache/Calamares/Calamares/Calamares.log" 
13:33:43 [1]: Using Calamares settings file at "/usr/share/calamares/settings.conf" 
13:33:43 [0]: ASSERT: "config.IsMap()" in file /buildsys/apps/calamares/src/calamares/src/libcalamaresui/Settings.cpp, line 61
13:33:44 [1]: Arguments list: "/usr/bin/../libexec/calamares_crash_reporter, /tmp/7a95b45f-72dd-c510-4f03806c-57a25a90.dmp, 4818, 6, Calamares, /usr/bin/calamares, 3.1.0.20170409-git-master-e44b7e3, 4818" 

 * Installed System: `/var/log/installation.log`
I can't install.

CPU of the first machine is an AMD E350
CPU of the second machine is an Intel Pentium J3710

**Comment by realloki** [comment]
/usr/share/calamares/settings.conf
Line 61
Is there a - missing at the beginning of that line?
instead of:
sequence:
it might be:
- sequence:

**Comment by demmm** [comment]
Make sure to check the md5 of the downloaded ISO and verify the integrity of the ISO burn ( right click option in Dolphin in KaOS Live mode).

**Comment by realloki** [comment]
The md5 sums are verified and correkt.

$md5sum KaOS-2017.04-x86_64.iso
947c82e90bfd7d9f4e26a295b428a553  KaOS-2017.04-x86_64.iso
947c82e90bfd7d9f4e26a295b428a553 (md5 sum from homepage)

$md5sum KaOS_Wayland-2017.04-x86_64.iso
4de88aea40041a2cf4bbb4e4b8df5906  KaOS_Wayland-2017.04-x86_64.iso
4de88aea40041a2cf4bbb4e4b8df5906 (md5 sum from homepage)

BTW it is really improbably that two different iso image downloads 
produce the same error.

I did not burn the iso. I dd'ed them onto an USB-Stick.

Am 21.04.2017 um 16:56 schrieb demmm:

**Comment by demmm** [comment]
Since this is not a reproducible error so far, first check has to be the Live media creation.
So if you use dd from different downloads, the integrity check of the ISO burn (to USB) is needed, to make sure you don not have a failing USB stick.

**Comment by realloki** [comment]
I tested a little further.

As I could see the ISOs are correctly transfered I tested to dd it to 
another USB stick.

Same result.

Crash number:
76f8e30a-00ba-6274-58627046-6b94a3fd

This time I tested only one machine. I did no update before starting 
installation. Last time there was no update for calamares anyway.


Am 06.05.17 um 00:14 schrieb demmm:

**Comment by demmm** [comment]
DO NOT update the Live session, when API changes happen a reboot is needed, which is not possible for live mode updates.  Certainly do not update Calamares alone, since that would explain your issue, it is build on new boost, thus can't run with old version.

**Comment by realloki** [comment]
It does not work in any case... with or without updates. I tested both 
cases. First without, after that with updates. It does not change this 
behavior. I tested this for a chance of getting rid of this error.

Am 06.05.17 um 17:20 schrieb demmm:

**Comment by ShalokShalom** [comment]
Is this still the case with the current ISO?

**Comment by demmm** [comment]
Since no further response from submitter, assuming this issue is now resolved.
