### ISSUE TITLE
Boost.Python fails on casual install

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/calamares#81]
#### Submission type

  - [ x] Bug report

#### Info regarding which version of Calamares is used, which Distribution

> 3.1.104 

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

installation.log https://pastebin.com/tFAMEmwE

blkid: https://pastebin.com/raw/ULGvLSzj
fdisk -l https://pastebin.com/XPs4atTZ

SysInfo: https://ptpb.pw/idrB

**Comment by demmm** [comment]
What is 'casual` install?
As the images linked in IRC show, the partitioning of this drive is broken, kpmcore cannot work with them, as shown with not being able to use the replace option.  Looks like the shrinking done in Windows severely damaged the layout.  Adding a 21 Mb in the wrongly resized partition does not fix any, the alignment will have to be fixed first.
As long as kpmcore cannot use XFS partitions in any of the automated options, keep on re-installing will always result in a broken install.
This bug report can stay open for a bit, but as noted in the above, the partitioning is broken, no installer can work with it as is.

**Comment by ShalokShalom** [comment]
Casual means in this case a installation on real hardware, as opposed to a virtual machine. :)

You asked me to open an own bug report for this very reason, which is why I use the word casual for it. Sorry for not putting it clear. :)

**Comment by ShalokShalom** [comment]
I guess I can close this? 

Since its solved here: https://github.com/KaOSx/calamares/issues/80

**Comment by demmm** [comment]
With the info you provided on IRC and the mention it also fails for you on ext4, yours is a different issue.  The other bug report has no issue with using any XFS partition for automated install for example.  For you that is shown with a red error/not possible to select.

**Comment by ShalokShalom** [comment]
No, the ext issue is different

**Comment by ShalokShalom** [comment]
I check it with the next ISO.

**Comment by demmm** [comment]
OK, closing then, since new xfsprogs in the build repo has the fix now too.

**Comment by demmm** [comment]
You can use the minimal ISO from the last test cycle, that one still had older xfsprogs on it:
https://sourceforge.net/projects/kaos-test/files/iso/KaOS-2018.04.24-x86_64.iso
