### ISSUE TITLE
No such file or directory: '/tmp/calamares-root-nv2qvwd3/boot/loader/entries/KaOS_2018.06.conf'

### ISSUE THREAD

**Issue by mikethewolf83** [KaOSx/calamares#82]
#### Submission type

  * Bug report

#### Info regarding which version of Calamares is used, which Distribution

> KaOS 2018.06 with Calamares version 3.2.0-2

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> Disk /dev/sda: 596.2 GiB, 640135028736 bytes, 1250263728 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 4096 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> Disklabel type: dos
> Disk identifier: 0x1770ce68
> 
> Device     Boot      Start        End    Sectors   Size Id Type
> /dev/sda1             2048    2000094    1998047 975.6M ef EFI (FAT-12/16/32)
> /dev/sda2          2002942  202000383  199997442  95.4G  5 Extended
> /dev/sda3       1246263296 1250263039    3999744   1.9G 82 Linux swap / Solari
> /dev/sda4        202000384 1246263295 1044262912   498G 83 Linux
> /dev/sda5          2004990  202000383  199995394  95.4G 83 Linux
> 
> Partition 2 does not start on physical sector boundary.
> Partition 5 does not start on physical sector boundary.
> Partition table entries are not in disk order.

#### What do you expect to have happen when Calamares installs?

> KaOS 2018.06 installs properly

#### Describe the issue you encountered

> La instalación ha fallado

> Error de Boost.Python en la tarea "bootldr".
> <class 'FileNotFoundError'>
> [Errno 2] No such file or directory: '/tmp/calamares-root-nv2qvwd3/boot/loader/entries/KaOS_2018.06.conf'
> 
> Traceback:
> File "/usr/lib/calamares/modules/bootldr/main.py", line 222, in run
>     install_bootloader(boot_loader, fw_type)
> 
>   File "/usr/lib/calamares/modules/bootldr/main.py", line 203, in install_bootloader
>     create_conf(uuid, conf_path)
> 
>   File "/usr/lib/calamares/modules/bootldr/main.py", line 97, in create_conf
>     with open(conf_path, 'w') as f:

#### Steps to reproduce the problem

> When installed with squid, just after the installer is creating the user, throws this problem and can not follow the installation procedure

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> https://github.com/mikethewolf83/mikethewolf83.github.io/blob/master/calamares.log

**Comment by demmm** [comment]
Two questions, how was the ISO created?  And what did you use for partitioning, automated or manual?

**Comment by mikethewolf83** [comment]
Thanks for answering, I already solved the problem. It happened that my hard drive had an MBR partition table, when I realized it, I changed it to **GPT** and solved the problem.
