### ISSUE TITLE
The installer failed to format partition /dev/VG/pv2_root on disk 'VG'.

### ISSUE THREAD

**Issue by Mizuho32** [KaOSx/calamares#84]
**Version and environment**
- KaOS-2019.09-x86_64.iso
- calamares 3.2.13.20190904-git-master-488ee03
- [octopi-sysinfo-1129199776.log](https://pastebin.com/DEjEFLns)

**Describe the bug**
Installation on LVM partition fails with the message "The installer failed to format partition /dev/VG/pv2_root on disk 'VG'."

**To Reproduce**
1. Install KaOS under the condition,
  - / on LV
  - /usr on LV
  - /var on LV

**Expected behavior**
System installed

**Screenshots and Logs**
- [installation.log](https://pastebin.com/UrxtbFXk)
![Screenshot_20191102_225119](https://user-images.githubusercontent.com/5453161/68071964-7252f480-fdc3-11e9-8b50-1db8944646b7.png)

**Related case and discussion**
As in the log, calamares deactivates the LVM partitions before formatting even if they are used as  install partition, maybe this is the cause.
> 22:50:37 [6]: ClearMountsJob finished. Here's what was done:
 "Successfully closed mapper device /dev/mapper/VG-LFS.\nSuccessfully closed mapper device /dev/mapper/VG-pv2_home.\nSuccessfully closed mapper device /dev/mapper/VG-pv2_root.\nSuccessfully closed mapper device /dev/mapper/VG-pv2_usr.\nSuccessfully closed mapper device /dev/mapper/VG-pv2_var.\nSuccessfully closed mapper device /dev/mapper/VG-v_home.\nSuccessfully closed mapper device /dev/mapper/VG-v_root.\nSuccessfully closed mapper device /dev/mapper/VG-v_usr.\nSuccessfully closed mapper device /dev/mapper/VG-v_var.\nSuccessfully disabled volume group VG." 

LVM status after calamares crash.
```bash
  LifeBook10.lan  live  ~  sudo lvscan
  inactive          '/dev/VG/v_root' [8.00 GiB] inherit
  inactive          '/dev/VG/v_usr' [40.00 GiB] inherit
  inactive          '/dev/VG/v_var' [5.00 GiB] inherit
  inactive          '/dev/VG/v_home' [42.00 GiB] inherit
  inactive          '/dev/VG/LFS' [15.00 GiB] inherit
  inactive          '/dev/VG/pv2_usr' [10.00 GiB] inherit
  inactive          '/dev/VG/pv2_var' [10.00 GiB] inherit
  inactive          '/dev/VG/pv2_home' [13.00 GiB] inherit
  inactive          '/dev/VG/pv2_root' [5.00 GiB] inherit
```

Below is the same case of Manjaro maybe.
https://forum.manjaro.org/t/problem-installing-manjaro-18-0-4-using-calamares-in-a-lvm-environment/87501
In that thread, the latest version of calamares solves the problem(?).
Actually, the version of calamares on Manjaro is new (calamares 3.2.15-2).

**Comment by demmm** [comment]
Why use an old ISO?  Issue still present in current ISO?
https://kaosx.us/news/2019/kaos10/

**Comment by Mizuho32** [comment]
Oh, I didn't notice.
I'll try it.

**Comment by demmm** [comment]
Nevermind, the Calamares bug tracker is full of these kinds of issues, no fix as far as I can see, examples:
https://github.com/calamares/calamares/issues?utf8=%E2%9C%93&q=lvm
https://github.com/calamares/calamares/issues/1163
So, nothing can be done here for this (will leave the issue open as reference), upstream needs to implement/address.

**Comment by Mizuho32** [comment]
OK thank you and calamares 3.2.14 doesn't solve the problem 😓

**Comment by demmm** [comment]
Please check if this issue is now fixed with calamares 3.19, test ISOs available:
https://forum.kaosx.us/d/2570-test-cycle-2020-02-iso/7

**Comment by Mizuho32** [comment]
I tested and I couldn't start calamares due to module "partition" keeps remaining.
I faced the same problem with calamares on Manjaro latest.

`$ calamares -d` log:
https://pastebin.com/UTr8YfEX

Of course, I checked SHA256SUM.

**Comment by abucodonosor** [comment]
@Mizuho32 

Don't even try LVM it is broken upstream in kpmcore already.
Won't work no matter how hard you are trying.

**Comment by Mizuho32** [comment]
@abucodonosor You mean, recent kpmcore is broken so we can't use recent calamares for LVM?
Actually, I could launch & install Manjaro 17.1.12.

**Comment by abucodonosor** [comment]
@Mizuho32 

Support for LVM in both kpmcore & calamares is incomplete and broken all over the place.

**Comment by Mizuho32** [comment]
@abucodonosor 😭

**Comment by demmm** [comment]
Closing as this thread is too much about upstream and other distros. Was a known upstream issue from the start.
