### ISSUE TITLE
Strange installation problems

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/calamares#85]
Hello!
I am satisfy KaOS Linux on my Dell Optiplex 760 and Dell Latitude D630 (first desktop second laptop both Intel Core 2 Duo).
But I bought new laptop called Hyperbook. You can see (and buy) it on this page:
https://tinyurl.com/towknj3
This is screenshot from UEFI Bios with info about its main components:
![IMG_20191220_174225552](https://user-images.githubusercontent.com/44374677/71277466-55638800-2355-11ea-85a3-e33680642d78.jpg)
Yesterday I struggle few hours to force KaOS installer to work. Without success.
It boot to main menu and failed load linux kernel - it only shows:
sha256 verified
No mater how I tune kernel command line - nothing helps (I disable other drivers, enable logs, force to use xwindow, type: random.trust_cpu=1 - in many combinations). I also dissable and enable secure boot. Suprisingly when I disable secure boot and clear all its data (in UEFI menu) I note that KaOS installer add sha256 key with all zeros to Administer Secure Boot -> DBX Option
So I try Kubuntu 19.10 - and it install without any problems!
Today I decide to report my problems with KaOS installer (because I am highly motivated user - I appreciate your effort and I am donor to KaOS budget). So I write KaOS installer image to my USB stick and try to boot. Surprisingly it started! But after this I was unable to connect to WiFi - no networks found. But I try once more start KaOS installer but this time without other video drivers than Intel and with proprietary drivers. This time I see my networks but they were greyed out and this was hardly even to highlight (after move mouse over network)  to see "Connect" button. This look like this:
![IMG_20191220_180856418](https://user-images.githubusercontent.com/44374677/71278176-21896200-2357-11ea-89e4-b7e71d69213d.jpg)
I not try installation with out network - this is probably use less and I don't suppose to solve this problems after installation.
Please let me know how to install KaOS with network. I want use it an I will pay for it as long as I can afford.

**Comment by demmm** [comment]
It is not needed to be connected to a network for a successful install, just a few automated settings (like location) are disabled.
Not clear from your report if you know that secure boot is not supported for KaOS.
Also, which ISO are using?  If it is a kernel issue, you can try and see if the latest test ISO (with linux 5.4.5) is better.  You can't install though with that ISO yet, see https://forum.kaosx.us/d/2526-test-cycle-2019-12-iso

**Comment by demmm** [comment]
No further response from submitter, closing.
