### ISSUE TITLE
Module bootldr should support partition number > 9 like /dev/sda10

### ISSUE THREAD

**Issue by dufresnep** [KaOSx/calamares#87]
**Is your feature request related to a problem? Please describe.**
Bootldr module have a for loop to find a boot partition.
This loop suppose that the partition number is a single digit.

**Describe the solution you'd like**
I'd like it to support multiple digits numbers, like /dev/sda143.

**Describe alternatives you've considered**
I once edited main.py to have:
```
        for partition in partitions:
            if partition["mountPoint"] == "/boot":
                libcalamares.utils.debug(partition["device"])
                boot_device = partition["device"]
                boot_p = ''.join([s for s in boot_device if s.isdigit()])
                device = ''.join([s for s in boot_device if not s.isdigit()])
```
where the last two lines are my proposed change...
it could be problematic with a device like /dev/hd2p3 where it would give boot_p of 23, and device /dev/hdp... but I don't really know such device names in use.

**Additional context**
I have just cloned this repository, and will try to get a pull request (which I am not used to do).

**Comment by dufresnep** [comment]
See https://github.com/KaOSx/calamares/pull/88

**Comment by demmm** [comment]
Implemented with https://github.com/KaOSx/calamares/commit/324236624d0da4284f8836328be4a6772da84f48
