### ISSUE TITLE
Typos in welcome screenshot (RTL) 

### ISSUE THREAD

**Issue by tomer** [KaOSx/calamares#89]
A screenshot of the KaOS is available on Calamares website but unfortunately has major typos with RTL languages. 

![image](https://user-images.githubusercontent.com/50206/129462535-e7a27562-2b14-46fe-9eb9-53f4fdad8030.png)

Resource: https://github.com/KaOSx/calamares/blob/master/src/branding/kaos_branding/languages.png

![image](https://user-images.githubusercontent.com/50206/129462603-fb9e8f53-dd63-40c4-8abd-5d16e9f28856.png)

a. The Hebrew word for Hello is שלום (Shalom), not םולש. As it is written top-down, it is expected to read by turning the head to the left, not to the right as with LTR languages such as English.
b. There is a Yiddish translation for Hello as העלא in Google Translate (the screenshot has אלעה), but I suspect it is not widely used by Yiddish speakers.
c. Arabic word سلام (Salam) is reversed as well.
d. Unrecognized parse above Yiddish. Is it Persian? @yarons can you recognize it? 

(Same issue reported on upstream as well https://github.com/calamares/calamares/issues/1751)

**Comment by demmm** [comment]
New images will be used on the Calamares site (I will close the issue there once done). Those show some modules no longer in use in KaOS.
However, this Welcome image will stay here, has been in use for over 7 years without anyone noticing, and not that easy to find such an image with many languages welcoming you.
Should you know of such an image, without this RTL issue, by all means, submit it here.

**Comment by NaftoliOst** [comment]
העלא is the transliteration of Hello.
The widely used greeting in Yiddish is "א גוטן"

**Comment by yarons** [comment]
There's both abahraM (Reversed Marahaba) and malaS (Reversed Salam), Marhaba is Welcome while Salam means Hello, both can be used in Arabic, For Persian I'm pretty sure that the right term in Khosh Amadid (خوش آمدید while خ is the first letter and د is the last one).

**Comment by demmm** [comment]
Image was replaced.
