### ISSUE TITLE
Grub doesn't install/boot on XFS

### ISSUE THREAD

**Issue by na5810** [KaOSx/calamares#95]
**Describe the bug**
I'm on a 64-bit laptop (Thinkpad X201), BIOS only. I tried to install KaOS from the January USB, but kept failing to install (grub-install saying "unknown filesystem") or boot (drops into Grub rescue due to "unknown filesystem"). It finally worked when the root filesystem was changed from XFS to EXT4.

**Screenshots and Logs**
I'm sorry... I didn't save the logs and now it's working (on EXT4). I just wanted to report in case this is useful.

Thank you!

**Comment by demmm** [comment]
This was a known issue in grub prior to 2.12, not an issue with the installer Calamares.
Latest ISO from March contains fixed grub, please always use the latest ISO.

**Comment by na5810** [comment]
Thanks! Was using the January ISO as had already downloaded it, glad to know it's fixed
